all: q1 q2 q4

clean:
	rm -f null

q1: null.c
	gcc -o null null.c
	./null

q2: null.c
	gcc -g null.c -o null
	gdb null

q4: q4.c
	gcc -o q4 q4.c
	
q5: q5.c
	gcc -o q5 q5.c
	
q6: q6.c
	gcc -o q6 q6.c
	

q7: q7.c
	gcc -o q7 q7.c

q8: q8.c
	gcc -o q8 q8.c
	./q8